language: c

env:
  - LUA=lua5.1                  LUAVER=5.1
  - LUA=lua5.2                  LUAVER=5.2

# Tool setup.
install:
  - sudo apt-get install -qq lua5.1
  - sudo apt-get install -qq lua5.2
  - git clone git://github.com/fperrad/lua-TestMore.git
  - sudo make -C lua-TestMore install LUAVER="$LUAVER"
  - git clone git://github.com/fperrad/lua-Coat.git
  - sudo make -C lua-Coat install LUAVER="$LUAVER"
  - git clone git://github.com/fperrad/lua-CodeGen.git
  - sudo make -C lua-CodeGen install LUAVER="$LUAVER"

# Build and test.
script:
  - make LUA="$LUA" unit_test
  - export LUA_PATH=";;./src/?.lua;./runtime/lua/?.lua;./t/lua/?.lua"
  - prove t/lua.t
  - prove t/c.t t/c++.t t/java.t t/perl.t t/python.t t/ruby.t

branches:
  only:
    - master

