
require 'Coat'

singleton 'Smc.Groovy'
extends 'Smc.Language'

has.id              = { '+', default = 'GROOVY' }
has.name            = { '+', default = 'Groovy' }
has.option          = { '+', default = '-groovy' }
has.suffix          = { '+', default = 'Context' }
has.generator       = { '+', isa = 'Smc.Groovy.Generator',
                        default = function () return require 'Smc.Groovy.Generator' end }
has.reflectFlag     = { '+', default = true }
has.serialFlag      = { '+', default = true }
has.syncFlag        = { '+', default = true }


class 'Smc.Groovy.Generator'
extends 'Smc.Generator'

has.suffix          = { '+', default = 'groovy' }

function method:_build_template ()
    return CodeGen{
        TOP = [[
// ex: set ro:
// DO NOT EDIT.
// generated by smc (http://github.com/fperrad/lua-Smc)
// from file : ${fsm.filename}

// Local variables:
//  buffer-read-only: t
// End:
]],
    }
end

