
require 'Coat'

singleton 'Smc.Php'
extends 'Smc.Language'

has.id              = { '+', default = 'PHP' }
has.name            = { '+', default = 'PHP' }
has.option          = { '+', default = '-php' }
has.suffix          = { '+', default = '_sm' }
has.generator       = { '+', isa = 'Smc.Php.Generator',
                        default = function () return require 'Smc.Php.Generator' end }
has.reflectFlag     = { '+', default = true }


class 'Smc.Php.Generator'
extends 'Smc.Generator'

has.suffix          = { '+', default = 'php' }

function method:_build_template ()
    return CodeGen{
        TOP = [[
/*
 ex: set ro:
 DO NOT EDIT.
 generated by smc (http://github.com/fperrad/lua-Smc)
 from file : ${fsm.filename}
*/

/*
 Local variables:
  buffer-read-only: t
 End:
*/
]],
    }
end
