
require 'Coat'

singleton 'Smc.Python'
extends 'Smc.Language'

has.id              = { '+', default = 'PYTHON' }
has.name            = { '+', default = 'Python' }
has.option          = { '+', default = '-python' }
has.suffix          = { '+', default = '_sm' }
has.generator       = { '+', isa = 'Smc.Python.Generator',
                        default = function () return require 'Smc.Python.Generator' end }
has.reflectFlag     = { '+', default = true }


class 'Smc.Python.Generator'
extends 'Smc.Generator'

has.suffix          = { '+', default = 'py' }

function method:_build_template ()
    return CodeGen{
        TOP = [[
# ex: set ro:
# DO NOT EDIT.
# generated by smc (http://github.com/fperrad/lua-Smc)
# from file : ${fsm.filename}

# Local variables:
#  buffer-read-only: t
# End:
]],
    }
end
